import type { GameLogEntry, GameLogNight } from "../pages/gameRoles/socketEvents";

type MockEntryByType = {
  [Type in GameLogEntry["type"]]: Extract<GameLogEntry, { type: Type }>;
};

const entryByType: MockEntryByType = {
  wolf_vote: {
    type: "wolf_vote",
    phase: "night",
    voteBreakdown: [{ targetId: "targetId", voterIds: ["actorId"] }],
  },
  day_vote: {
    type: "day_vote",
    phase: "day",
    voteBreakdown: [{ targetId: "targetId", voterIds: ["actorId"] }],
  },
  day_vote_skipped: { type: "day_vote_skipped", phase: "day" },
  wolf_result: {
    type: "wolf_result",
    phase: "night",
    targetIds: ["targetId"],
    selectedByByTarget: { targetId: ["actorId"] },
  },
  day_result: { type: "day_result", phase: "day", targetId: "targetId" },
  trial_started: { type: "trial_started", phase: "day", targetId: "targetId" },
  trial_verdict: {
    type: "trial_verdict",
    phase: "day",
    targetId: "targetId",
    liveVotes: 1,
    dieVotes: 1,
    liveVoterIds: ["voterId"],
    dieVoterIds: ["actorId"],
    executed: true,
  },
  coffee_maker_search: {
    type: "coffee_maker_search",
    phase: "night",
    actorId: "actorId",
    targetIds: ["targetId", "sourceId"],
  },
  coffee_herb_search: {
    type: "coffee_herb_search",
    phase: "night",
    actorId: "actorId",
    targetId: "targetId",
    herbRole: "Linh Chi",
  },
  bonus_bite: { type: "bonus_bite", phase: "night" },
  night_action_extra_time: {
    type: "night_action_extra_time",
    phase: "night",
    targetId: "targetId",
    roleName: "Vai trò",
    extraSeconds: 30,
  },
  guardian_protect: { type: "guardian_protect", phase: "night", actorId: "actorId", targetId: "targetId" },
  protector_bless: {
    type: "protector_bless",
    phase: "night",
    actorId: "actorId",
    targetId: "targetId",
    permanent: true,
  },
  protector_save: {
    type: "protector_save",
    phase: "night",
    actorId: "actorId",
    targetId: "targetId",
    cause: { type: "wolf", attackerIds: ["sourceId"] },
    permanent: true,
  },
  village_chief_revealed: {
    type: "village_chief_revealed",
    phase: "day",
    targetId: "targetId",
    reason: "day_vote",
  },
  village_chief_delayed_death: { type: "village_chief_delayed_death", phase: "night", targetId: "targetId" },
  village_chief_extra_vote_started: {
    type: "village_chief_extra_vote_started",
    phase: "day",
    chiefId: "chiefId",
  },
  witch_heal: { type: "witch_heal", phase: "night", actorId: "actorId", targetId: "targetId" },
  witch_poison: { type: "witch_poison", phase: "night", actorId: "actorId", targetId: "targetId" },
  seer_check: { type: "seer_check", phase: "night", actorId: "actorId", targetId: "targetId", isWolf: true },
  hunter_mark: { type: "hunter_mark", phase: "night", actorId: "actorId", targetId: "targetId" },
  hunter_shot: { type: "hunter_shot", phase: "night", actorId: "actorId", targetId: "targetId" },
  cursed_sniff: {
    type: "cursed_sniff",
    phase: "night",
    actorId: "actorId",
    targetId: "targetId",
    hasWolf: true,
    areaIds: ["targetId", "sourceId"],
  },
  merchant_trade_offer: {
    type: "merchant_trade_offer",
    phase: "night",
    actorId: "actorId",
    targetId: "targetId",
    itemId: "iron-armor",
    merchantChoice: "up",
  },
  merchant_trade_response: {
    type: "merchant_trade_response",
    phase: "night",
    actorId: "actorId",
    targetId: "targetId",
    itemId: "iron-armor",
    merchantChoice: "up",
    targetChoice: "up",
    result: "success",
  },
  merchant_item_received: {
    type: "merchant_item_received",
    phase: "night",
    targetId: "targetId",
    itemId: "iron-armor",
    appliesNight: 2,
  },
  merchant_item_expired: {
    type: "merchant_item_expired",
    phase: "night",
    targetId: "targetId",
    itemIds: ["iron-armor"],
  },
  merchant_item_used: {
    type: "merchant_item_used",
    phase: "night",
    itemId: "gunpowder-barrel",
    actorId: "actorId",
    targetId: "targetId",
    sourceId: "sourceId",
  },
  merchant_win_condition_completed: {
    type: "merchant_win_condition_completed",
    phase: "night",
    actorId: "actorId",
    successfulTrades: 3,
    requiredTrades: 3,
  },
  angel_revive_activated: {
    type: "angel_revive_activated",
    phase: "night",
    actorId: "actorId",
    targetId: "targetId",
    guess: "villagers",
  },
  angel_revive_choice: {
    type: "angel_revive_choice",
    phase: "night",
    actorId: "actorId",
    targetId: "targetId",
    guess: "villagers",
    targetTeam: "villagers",
  },
  angel_revive_revealed: {
    type: "angel_revive_revealed",
    phase: "day",
    actorId: "actorId",
    targetId: "targetId",
  },
  angel_outcome: {
    type: "angel_outcome",
    phase: "day",
    actorId: "actorId",
    targetId: "targetId",
    guess: "villagers",
    targetTeam: "villagers",
    won: true,
    noContest: false,
    reason: "matched_villagers",
    winner: "villagers",
  },
  mysterious_force_eliminated: { type: "mysterious_force_eliminated", phase: "night", targetId: "targetId" },
  love_pair: {
    type: "love_pair",
    phase: "night",
    actorId: "actorId",
    targetId: "targetId",
    targetWolfAligned: false,
  },
  love_escape_vote: { type: "love_escape_vote", phase: "night", actorId: "actorId", partnerId: "partnerId" },
  love_escape_missed: { type: "love_escape_missed", phase: "night", actorId: "actorId", partnerId: "partnerId" },
  love_escape: { type: "love_escape", phase: "night", targetIds: ["actorId", "partnerId"] },
  love_link_death: { type: "love_link_death", phase: "day", sourceId: "sourceId", targetId: "targetId" },
  spirit_wolf_decision: { type: "spirit_wolf_decision", phase: "night", actorId: "actorId", saved: true },
  ban_soi_aligned: { type: "ban_soi_aligned", phase: "night", targetId: "targetId" },
  wild_wolf_conversion: {
    type: "wild_wolf_conversion",
    phase: "night",
    actorId: "actorId",
    targetId: "targetId",
    success: true,
    previousTargetRole: "Dân làng",
  },
  saved_by_guardian: { type: "saved_by_guardian", phase: "night", actorId: "actorId", targetIds: ["targetId"] },
  saved_by_witch: { type: "saved_by_witch", phase: "night", targetIds: ["targetId"] },
  eliminated: {
    type: "eliminated",
    phase: "day",
    targetIds: ["targetId"],
    causesByTarget: { targetId: [{ type: "witch_poison", sourceActorId: "actorId" }] },
  },
  no_death: { type: "no_death", phase: "night" },
  elemental_guess: {
    type: "elemental_guess",
    phase: "night",
    actorId: "actorId",
    targetId: "targetId",
    isCorrect: true,
  },
  elemental_guess_summary: {
    type: "elemental_guess_summary",
    phase: "night",
    correctCount: 1,
    totalCount: 1,
    correctIds: ["actorId"],
    triggeredBuffVote: true,
    nextBuffVoteNight: 2,
  },
  elemental_buff_vote: {
    type: "elemental_buff_vote",
    phase: "night",
    voteBreakdown: [{ buffId: "seer-check-two", voterIds: ["actorId"] }],
    chosenBuffId: "seer-check-two",
    tier: 4,
    chosenVoterIds: ["actorId"],
  },
  elemental_buff: { type: "elemental_buff", phase: "night", buffId: "seer-check-two", tier: 4 },
  custom_log: { type: "custom_log", phase: "day", message: "Nội dung log tùy chỉnh" },
  host_ended_game: { type: "host_ended_game", phase: "day" },
  soi_mu_villager_choose: {
    type: "soi_mu_villager_choose",
    phase: "night",
    actorId: "actorId",
    targetId: "targetId",
  },
  soi_mu_wolf_bite: {
    type: "soi_mu_wolf_bite",
    phase: "night",
    actorId: "actorId",
    targetId: "targetId",
    wolfLabel: "Sói A",
  },
  soi_mu_wolf_suicide: {
    type: "soi_mu_wolf_suicide",
    phase: "night",
    actorId: "actorId",
    wolfLabel: "Sói A",
  },
  soi_mu_wolf_inactive_choose: {
    type: "soi_mu_wolf_inactive_choose",
    phase: "night",
    actorId: "actorId",
    targetId: "targetId",
    wolfLabel: "Sói B",
    activeWolfLabel: "Sói A",
  },
  soi_mu_ariana_trade: {
    type: "soi_mu_ariana_trade",
    phase: "night",
    actorId: "actorId",
    targetId: "targetId",
    actorThumb: "up",
    targetThumb: "down",
  },
  song_trung_rob: {
    type: "song_trung_rob",
    phase: "night",
    actorId: "actorId",
    targetId: "targetId",
    victimRole: "Dân làng",
    cupidId: "cupidId",
    staysAlive: true,
  },
};

const nightCustomLogEntries: GameLogEntry[] = [
  { type: "custom_log", phase: "night", message: "__song_trung_victim_muted__:targetId:cupidId" },
  { type: "custom_log", phase: "night", message: "__song_trung_lovers_paired__:cupidId:actorId" },
  { type: "custom_log", phase: "night", message: "__song_trung_rob_single__:actorId:targetId:Dân làng:false" },
  { type: "custom_log", phase: "night", message: "__song_trung_guess_wrong__:actorId:targetId" },
  { type: "custom_log", phase: "night", message: "__song_trung_victim_guess_wrong__:actorId:targetId" },
  {
    type: "custom_log",
    phase: "night",
    message: "[Cặp đôi bỏ trốn] Thợ săn bắn targetId nhưng không trúng do cặp đôi đã quyết định ra khỏi làng.",
  },
  { type: "custom_log", phase: "night", message: "Trưởng làng đỡ thay vết cắn của Sói cho Hộ nhân." },
  {
    type: "custom_log",
    phase: "night",
    message: "[Cặp đôi bỏ trốn] targetId đã né được vết cắn của Sói do cặp đôi quyết định ra khỏi làng trong đêm.",
  },
  {
    type: "custom_log",
    phase: "night",
    message: "[Cặp đôi bỏ trốn] targetId đã né được bình độc của Phù thủy do cặp đôi quyết định ra khỏi làng trong đêm.",
  },
  {
    type: "custom_log",
    phase: "night",
    message: "targetId đã bị vô hiệu chức năng vì bị dính những niềm đau từ Đàn bà mang tới.",
  },
  { type: "custom_log", phase: "night", message: "Trưởng làng đã bị cắn nhưng chưa chết." },
  { type: "custom_log", phase: "night", message: "targetId bị cắn và mất 1 tim." },
  {
    type: "custom_log",
    phase: "night",
    message: "Song Trùng chọn trúng partner của Thần tình yêu, nhưng cặp đôi đã ra khỏi làng đêm nay nên không có gì xảy ra.",
  },
  { type: "custom_log", phase: "night", message: "Thầy bói kiểm tra hai người chơi, kết quả: Yes." },
  { type: "custom_log", phase: "night", message: "Nuôi quạ kiểm tra một người chơi, vai trò nhận được: Dân làng." },
  {
    type: "custom_log",
    phase: "night",
    message: "Người bị cướp chức năng (targetId) đã tìm đúng Song Trùng (actorId)!",
  },
  {
    type: "custom_log",
    phase: "night",
    message: "Trưởng làng tìm kiếm Hộ nhân: chọn [targetId] và kết quả là ĐÚNG.",
  },
  { type: "custom_log", phase: "night", message: "Trưởng làng đã tìm thấy Hộ nhân!" },
];

const dayCustomLogEntries: GameLogEntry[] = [
  entryByType.custom_log,
  {
    type: "custom_log",
    phase: "day",
    message: "Đoản hậu sớm: Phe dân chỉ còn 2 người nhưng không còn ai có khả năng tự vệ. Sói thắng.",
  },
  {
    type: "custom_log",
    phase: "day",
    message: "Song Trùng đã chết nhưng người bị cướp vai trò chưa tìm thấy Song Trùng. Thần tình yêu sẽ chết theo.",
  },
  {
    type: "custom_log",
    phase: "day",
    message: "Song Trùng chết do nguyên nhân khác biểu quyết treo cổ. Điều kiện giải cứu không hợp lệ.",
  },
  {
    type: "custom_log",
    phase: "day",
    message: "Song Trùng bị treo cổ nhưng Thần tình yêu không vote chết Song Trùng. Điều kiện giải cứu không hợp lệ.",
  },
  {
    type: "custom_log",
    phase: "day",
    message: "[Giải cứu thành công] Song Trùng đã chết. targetId lấy lại được chức năng vai trò của mình.",
  },
  {
    type: "custom_log",
    phase: "day",
    message: "targetId đã bị Nam Thư chọn và sẽ không thể cười vì có cái gì mà buồn cười.",
  },
  {
    type: "custom_log",
    phase: "day",
    message: "targetId đã bị Suy Thận chọn và sẽ không thể đi đái nếu không sẽ nổ và chết.",
  },
  { type: "custom_log", phase: "day", message: "Diệt quỷ bắn trượt targetId." },
  { type: "custom_log", phase: "day", message: "targetId đã chết do cười vì có cái gì mà buồn cười." },
  { type: "custom_log", phase: "day", message: "targetId đã chết do đi đái khi Suy Thận còn sống." },
  {
    type: "custom_log",
    phase: "day",
    message: "Người chơi bị điều tra đã chọn đúng mục tiêu cũ. Sự trong sạch được làm rõ.",
  },
  {
    type: "custom_log",
    phase: "day",
    message: "Người chơi bị điều tra chọn sai mục tiêu cũ và đã chết lập tức.",
  },
];

export const MOCK_8_GAME_LOG_NIGHTS: GameLogNight[] = [
  {
    night: 1,
    at: 0,
    entries: Object.values(entryByType).filter(
      (entry) => entry.type !== "custom_log" && entry.type !== "song_trung_rob",
    ),
  },
  {
    night: 2,
    at: 0,
    // ponytail: gom riêng custom_log và log Song Trùng sinh custom_log để dễ kiểm tra giao diện.
    entries: [entryByType.song_trung_rob, ...nightCustomLogEntries, ...dayCustomLogEntries],
  },
];

export const MOCK_8_LOG_PLAYER_NAMES: Record<string, string> = {
  actorId: "actorId",
  targetId: "targetId",
  sourceId: "sourceId",
  voterId: "voterId",
  chiefId: "chiefId",
  partnerId: "partnerId",
  cupidId: "cupidId",
};
